### ISSUE TITLE
Unable to fetch projects 

### ISSUE THREAD

**Issue by hpahasini** [dilansalinda/compliance-guard-engine#10]
**Describe the bug**
I'm currently testing the data persistence flow in the [ProjectDataExtractorImpl.java](https://github.com/dilansalinda/compliance-guard-engine/blob/main/sonarqube-data-extractor/src/main/java/org/dilan/salinda/sonarqubedataextractor/service/impl/ProjectDataExtractorImpl.java) class. 
When I execute the save method with a populated `projectComponents` List, the following log occurs: `Unable to find Project project001 organization org001!!`. It seems like the code is attempting to find an organization key, but the table doesn't contain any organization information. However, when I manually save the organization key to the **organization** table, this issue does not occur.

**To Reproduce**
1. Execute the app using main method.
2. See error : `Unable to find Project project001 organization org001!!`

_`project001` is project and org001 is orgnization in my sonarcloud portal_ 

**Expected behavior**
Projects persistence to the **project** table and I**ssues, Issue tags** save to the database tables.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Compliance guard engine Version 0.0.1
- Spring Boot Version : 3.1.3
- MySQL Server Version : 8.1.0

**Comment by dilansalinda** [comment]
Issue fixed and merge into **main branch**
[hotfix](https://github.com/dilansalinda/compliance-guard-engine/pull/11)
